### ISSUE TITLE
Problem upgrading from 2.0.56 to 2.0.57

### ISSUE THREAD

**Issue by tommander** [tommander/factorio-updater#7]
Error when updating from 2.0.56 to 2.0.57:

```
Error Util.cpp:81: Error while loading utility-constants prototype "default" (utility-constants): Vibration file does not exist: __core__/sound/gui-game-controller-move.bnvib
Modifications: core › Elevated Rails › Space Age</output>
```

**Comment by tommander** [comment]
https://forums.factorio.com/viewtopic.php?p=674807

Create the missing file (and path) `/data/core/sound/gui-game-controller-move.bnvib` (can be empty) and restart the updater

**Comment by tommander** [comment]
There are two updates - `2.0.55->2.0.56` and `2.0.55->2.0.57`. The script should be able to pick the one with higher semver in case there are more paths.
